# Generated by Django 2.1.1 on 2018-11-06 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('aisle', models.IntegerField()),
                ('short_description', models.CharField(max_length=150)),
                ('item_number', models.IntegerField()),
            ],
            options={
                'ordering': ['name', 'item_number'],
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listname', models.CharField(default='DEFAULT', max_length=100)),
                ('item', models.ManyToManyField(to='shop.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favoriteCart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.List')),
                ('favoriteItems', models.ManyToManyField(to='shop.Item')),
				('user', models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Store'),
        ),
    ]
