# Generated by Django 2.1.1 on 2018-10-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20181029_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='list',
            name='listid',
        ),
        migrations.AddField(
            model_name='list',
            name='listname',
            field=models.CharField(default='DEFAULT', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='DEFAULT', max_length=200),
        ),
        migrations.AlterField(
            model_name='list',
            name='item',
            field=models.ManyToManyField(to='shop.Item'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='DEFAULT', max_length=100),
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
