# Generated by Django 2.1.1 on 2018-10-30 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20181029_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favoriteCarts',
        ),
        migrations.AddField(
            model_name='user',
            name='favoriteCart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.List'),
        ),
    ]
