# Generated by Django 2.1.1 on 2018-10-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='stock',
        ),
        migrations.AddField(
            model_name='store',
            name='items',
            field=models.ManyToManyField(to='shop.Item'),
        ),
    ]
